// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJGl9aRdyLruMa65ovJbnSAS7USo5gSo',
    appId: '1:951705674726:web:5768d18aaf742848d62c27',
    messagingSenderId: '951705674726',
    projectId: 'fluttersocmed-ebce7',
    authDomain: 'fluttersocmed-ebce7.firebaseapp.com',
    storageBucket: 'fluttersocmed-ebce7.firebasestorage.app',
    measurementId: 'G-BL8HVXCHYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOGfgpoVU7qy7CsVwn06VCWP-LEabOPE',
    appId: '1:951705674726:android:9ec5085b528f7fc7d62c27',
    messagingSenderId: '951705674726',
    projectId: 'fluttersocmed-ebce7',
    storageBucket: 'fluttersocmed-ebce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCFlVSJ0yBlS_wi-noDEF2trPjHBATnA',
    appId: '1:951705674726:ios:86a93da89a627a8dd62c27',
    messagingSenderId: '951705674726',
    projectId: 'fluttersocmed-ebce7',
    storageBucket: 'fluttersocmed-ebce7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationRazo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCFlVSJ0yBlS_wi-noDEF2trPjHBATnA',
    appId: '1:951705674726:ios:86a93da89a627a8dd62c27',
    messagingSenderId: '951705674726',
    projectId: 'fluttersocmed-ebce7',
    storageBucket: 'fluttersocmed-ebce7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationRazo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJGl9aRdyLruMa65ovJbnSAS7USo5gSo',
    appId: '1:951705674726:web:cad6c089e3cfdf41d62c27',
    messagingSenderId: '951705674726',
    projectId: 'fluttersocmed-ebce7',
    authDomain: 'fluttersocmed-ebce7.firebaseapp.com',
    storageBucket: 'fluttersocmed-ebce7.firebasestorage.app',
    measurementId: 'G-B45Z7VBCCQ',
  );

}