// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhppMHslt3aTnXN9giFxYuAddgOiyqnQ',
    appId: '1:3738446029:web:a4dec0520b7ee73fcd6184',
    messagingSenderId: '3738446029',
    projectId: 'fir-crudexam',
    authDomain: 'fir-crudexam.firebaseapp.com',
    databaseURL: 'https://fir-crudexam-default-rtdb.firebaseio.com',
    storageBucket: 'fir-crudexam.firebasestorage.app',
    measurementId: 'G-3NNXD15LCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGFcUBfPvqnTpsNaW5tHmWfgsqtbK7jWU',
    appId: '1:3738446029:android:63277eba6e88cd49cd6184',
    messagingSenderId: '3738446029',
    projectId: 'fir-crudexam',
    databaseURL: 'https://fir-crudexam-default-rtdb.firebaseio.com',
    storageBucket: 'fir-crudexam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HBRqCTKE2BgGgg1_Rw29LLj7O-tS690',
    appId: '1:3738446029:ios:cd7fa9f4c867a41dcd6184',
    messagingSenderId: '3738446029',
    projectId: 'fir-crudexam',
    databaseURL: 'https://fir-crudexam-default-rtdb.firebaseio.com',
    storageBucket: 'fir-crudexam.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HBRqCTKE2BgGgg1_Rw29LLj7O-tS690',
    appId: '1:3738446029:ios:cd7fa9f4c867a41dcd6184',
    messagingSenderId: '3738446029',
    projectId: 'fir-crudexam',
    databaseURL: 'https://fir-crudexam-default-rtdb.firebaseio.com',
    storageBucket: 'fir-crudexam.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIhppMHslt3aTnXN9giFxYuAddgOiyqnQ',
    appId: '1:3738446029:web:4fd7d96e44a28720cd6184',
    messagingSenderId: '3738446029',
    projectId: 'fir-crudexam',
    authDomain: 'fir-crudexam.firebaseapp.com',
    databaseURL: 'https://fir-crudexam-default-rtdb.firebaseio.com',
    storageBucket: 'fir-crudexam.firebasestorage.app',
    measurementId: 'G-RXXBS8WQJE',
  );
}
